# define Traefik configuration
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
  namespace: default
data:
  traefik.toml: |
    # traefik.toml
    insecureSkipVerify = true
    [log]
      level = "INFO"
    defaultEntryPoints = ["http", "https"]
    [accessLog]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "default/traefik-ingress-controller"